### PR TITLE
[FIX]#272 Fix broken docs css in mlf-core and templates

### PR DESCRIPTION
**Pull request by Imipenem**

### CODE REVIEW

**Comment by Imipenem** [comment]
@Zethson Unfortunately, I cannot think of an easier way to generalize this to work for any depth (altough I think more than 5 or at most 6 is not likely to happen anyways). Since I have to name the concret html element in the css code (so the `toctree-l` elements), this needs to be adjusted manually if we add more "levels".

**Comment by Zethson** [comment]
```
 0it [00:00, ?it/s]Traceback (most recent call last):
  File "exploding_springfield/exploding_springfield.py", line 62, in <module>
    dm.setup(stage='fit')
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 92, in wrapped_fn
    return fn(*args, **kwargs)
  File "/mlflow/projects/code/exploding_springfield/data_loading/data_loader.py", line 27, in setup
    self.df_train = datasets.MNIST('dataset', download=True, train=True, transform=self.transform)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 79, in __init__
    self.download()
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 146, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 256, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 84, in download_url
    raise e
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 70, in download_url
    urllib.request.urlretrieve(
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/user/miniconda/envs/exploding_springfield/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I've seen this several times already. We need to see whether this persists and if yes investigate it.

**Comment by Zethson** [comment]
@Imipenem please also push these fixes to CT

**Comment by Imipenem** [comment]
@Zethson seems like those are already included in CT ;)

**Pull request merged**
