### PR TITLE
Update autolog call to new general 1.12 autologging

### LINKED ISSUE #237: Refactor ML lib specific autologs into mlflow.autolog()
Since version 1.12 a new *general* autologging API exists.
https://github.com/mlflow/mlflow/releases/tag/v1.12.0

> Add universal mlflow.autolog which enables autologging for all supported integrations (#3561, #3590, @andrewnitu)

We should replace the manual calls of LIBRARY.AUTOLOG() in the respective templates with `mlflow.autolog()`. This should be a trivial change IF MLflow detects the correct library. Guess this just requires some trying out :)

### PR DESCRIPTION
**Pull request by Emiller88**
Fixes #237

### CODE REVIEW

**Comment by Zethson** [comment]
Did you test it?

**Comment by Emiller88** [comment]
Not yet, I figured the CI would be a good first pass.

**Comment by Zethson** [comment]
All right. I think that you have to manually test all templates to ensure that everything is logged as before. Really annoying task I know. But already have future plans to improve all of this testing with an EBI collaborator.  Friday, 12 February 2021, 05:07PM +01:00 from Edmund Miller  notifications@github.com :

**Comment by Emiller88** [comment]
Alright, so I was only able to test pytorch due to some cuda issues, and docker not being on installed on our GPU boxes. I also realized I didn't know how to check that everything is logged as before so I will need some help on this one.

**Comment by Zethson** [comment]
This issue is fine to only test it on the CPU.
Just run it once without the new change and once with. Then run "mlflow ui" in the root directory of the project. Look at your results in the web interface :) Both runs should have the same content.

**Comment by Emiller88** [comment]
Okay, had to do some port-forwarding, because testing this locally isn't an option(nixos) but it was a good exercise for running it on the GPU boxes anyways. Appears to look the same to me!

**Comment by Zethson** [comment]
> 
> 
> Okay, had to do some port-forwarding, because testing this locally isn't an option(nixos) but it was a good exercise for running it on the GPU boxes anyways. Appears to look the same to me!

Did you test Pytorch,TF and XGBoost?
If yes please fix the merge conflicts & update the changelog :)
You can also inlcude https://github.com/mlf-core/mlf-core/issues/157 here since it should now just be adding a single 1 as a parameter for the mlflow.autolog()!

**Review by Zethson — APPROVED** [review]
LGTM

**Pull request merged**
