### PR TITLE
Refactor mlf core singleton

### LINKED ISSUE #214: Refactor mlf_core.py into a Singleton class
kevin.mentosToday at 1:40 PM
What do you think about trying to hide some of the main reproducibility code a bit better from the user?
So the code for the randomness settings. Basically I'm getting a bit nervous seeing that pretty central lines of code sitting there in plain-text, waiting for some user to accidentally mix it up.
What about bundling these settings in a mlf-core class object, which can still be used to change them - it's just a bit harder.
Just a thought I had when looking at the code recently ... opinions?

ZethToday at 2:49 PM
mlf-core lint will shout at you if touch them in the wrong way. Actually, I encourage you to try to break it and if you can (I am sure that you will find ways) report them and we will fix them.

But yeah, hiding them into an object could actually be a good idea. So would you just create this object in the mlf_core.py file or where would you put it?
Maybe this object could then even be a different package?

kevin.mentosToday at 3:17 PM
In a way you would have a singleton class that stores those settings and also sets them/changes them. But there are coutnless ways of actually implementing this I guess

### PR DESCRIPTION
**Pull request by Emiller88**
Closes #214

### CODE REVIEW

**Comment by Zethson** [comment]
@Yeah, I think that this is going into the right direction.
Guess the linter needs to be fixed next to make the Pytorch workflow happy.
And then  move the Singleton class into {{ cookiecutter.common_mlflow }}, adapt it as described in the issue and adapt all templates.

Awesome!

**Comment by KevinMenden** [comment]
Nice :) 👍

**Comment by Emiller88** [comment]
Awesome! I was busy trying to get `act` to work last night so I can run the gh tests locally, since tox isn't failing but the create pytorch workflow is.

**Comment by Zethson** [comment]
> Awesome! I was busy trying to get `act` to work last night so I can run the gh tests locally, since tox isn't failing but the create pytorch workflow is.

Yeah. Ideally you can create templates on your local machine as well :)
Time to run
`mlf-core config`
and then
`mlf-core create`

tox isn't failing, because mlf-core has close to no tests. We did not yet have time to write them. However, most of the core functionality is cross tested in cookietemple. 
You can always click on the details of the corresponding Github Actions run to figure out what went wrong.

**Comment by Emiller88** [comment]
@Zethson I think this is about ready just need to fix the linter. Do you just want me to move the lines over from `expected_lines_pytorch_reproducibility` to ` expected_lines_sys_intell_conda_env`?

**Comment by Zethson** [comment]
> @Zethson I think this is about ready just need to fix the linter. Do you just want me to move the lines over from `expected_lines_pytorch_reproducibility` to ` expected_lines_sys_intell_conda_env`?

Don't quite get how you want to move them.
No, they are two distinct checks. 

> expected_lines_sys_intell_conda_env

is supposed to check that the hardware and conda environment are logged

> expected_lines_pytorch_reproducibility

checks that Pytorch reproducibility is ensured. I would like to keep them as two separate methods.

**Comment by Zethson** [comment]
@Emiller88 But just had a brief look at the code. This is exactly what I had in mind :) 
Good job!
Just ping me for a review when it's ready.

**Comment by Emiller88** [comment]
@Zethson I think I've either gotten it right, or broken the linting.

**Comment by Zethson** [comment]
@Imipenem the flake8 linting in the create workflows is not working! It should find errors here.

@Emiller88 Almost there! The flake8 linting is failing for the created projects.
-> Create a project and then run flake8 on it. What you get is: 
```
./exploding_springfield/mlf_core/mlf_core.py:27:5: E303 too many blank lines (2)
./exploding_springfield/mlf_core/mlf_core.py:34:5: E303 too many blank lines (2)
./exploding_springfield/mlf_core/mlf_core.py:40:5: E303 too many blank lines (2)
./exploding_springfield/mlf_core/mlf_core.py:47:25: E128 continuation line under-indented for visual indent
./exploding_springfield/mlf_core/mlf_core.py:48:25: E128 continuation line under-indented for visual indent
./exploding_springfield/mlf_core/mlf_core.py:49:25: E128 continuation line under-indented for visual indent
./exploding_springfield/mlf_core/mlf_core.py:50:25: E128 continuation line under-indented for visual indent
./exploding_springfield/mlf_core/mlf_core.py:55:5: E303 too many blank lines (2)
```
Since we don't want our users to start with failing worksflows we have to fix that.

**Comment by Imipenem** [comment]
@Zethson might be some pathing issue here, cannot test it atm, but can do it later.

**Comment by Zethson** [comment]
@Imipenem that would be very nice.
Maybe flake8 just doesn't work with path above it or something?

**Comment by Emiller88** [comment]
> @Imipenem the flake8 linting in the create workflows is not working! It should find errors here.
> 
> @Emiller88 Almost there! The flake8 linting is failing for the created projects.
> -> Create a project and then run flake8 on it. What you get is:
> 
> ```
> ./exploding_springfield/mlf_core/mlf_core.py:27:5: E303 too many blank lines (2)
> ./exploding_springfield/mlf_core/mlf_core.py:34:5: E303 too many blank lines (2)
> ./exploding_springfield/mlf_core/mlf_core.py:40:5: E303 too many blank lines (2)
> ./exploding_springfield/mlf_core/mlf_core.py:47:25: E128 continuation line under-indented for visual indent
> ./exploding_springfield/mlf_core/mlf_core.py:48:25: E128 continuation line under-indented for visual indent
> ./exploding_springfield/mlf_core/mlf_core.py:49:25: E128 continuation line under-indented for visual indent
> ./exploding_springfield/mlf_core/mlf_core.py:50:25: E128 continuation line under-indented for visual indent
> ./exploding_springfield/mlf_core/mlf_core.py:55:5: E303 too many blank lines (2)
> ```
> 
> Since we don't want our users to start with failing worksflows we have to fix that.

@Zethson That file shouldn't get created but for some reason it is. The correct path is `exploding_springfield/exploding_springfield/mlf_core/mlf_core.py`. I'm able to reproduce that it's getting created locally.

**Comment by Zethson** [comment]
> 
> 
> > @Imipenem the flake8 linting in the create workflows is not working! It should find errors here.
> > @Emiller88 Almost there! The flake8 linting is failing for the created projects.
> > -> Create a project and then run flake8 on it. What you get is:
> > ```
> > ./exploding_springfield/mlf_core/mlf_core.py:27:5: E303 too many blank lines (2)
> > ./exploding_springfield/mlf_core/mlf_core.py:34:5: E303 too many blank lines (2)
> > ./exploding_springfield/mlf_core/mlf_core.py:40:5: E303 too many blank lines (2)
> > ./exploding_springfield/mlf_core/mlf_core.py:47:25: E128 continuation line under-indented for visual indent
> > ./exploding_springfield/mlf_core/mlf_core.py:48:25: E128 continuation line under-indented for visual indent
> > ./exploding_springfield/mlf_core/mlf_core.py:49:25: E128 continuation line under-indented for visual indent
> > ./exploding_springfield/mlf_core/mlf_core.py:50:25: E128 continuation line under-indented for visual indent
> > ./exploding_springfield/mlf_core/mlf_core.py:55:5: E303 too many blank lines (2)
> > ```
> > 
> > 
> > Since we don't want our users to start with failing worksflows we have to fix that.
> 
> @Zethson That file shouldn't get created but for some reason it is. The correct path is `exploding_springfield/exploding_springfield/mlf_core/mlf_core.py`. I'm able to reproduce that it's getting created locally.

Think that it looks fine? Just need to fix flake8

**Comment by Emiller88** [comment]
There's two mlf_core files being created, `exploding_springfield/mlf_core/mlf_core.py` and `exploding_springfield/exploding_springfield/mlf_core/mlf_core.py`. The second is the one I intended to create, the first is getting created accidently.

**Comment by Zethson** [comment]
I cannot confirm or reproduce. Cannot see a reason for this in your PR either

**Comment by Emiller88** [comment]
You can't confirm whether the files are there or not, or do you mean that `exploding_springfield/exploding_springfield/mlf_core/mlf_core.py` does not exist?

**Comment by Zethson** [comment]
```
.
├── AUTHORS.rst
├── .bandit.yml
├── CHANGELOG.rst
├── CODE_OF_CONDUCT.rst
├── Dockerfile
├── docs
│   ├── authors.rst
│   ├── changelog.rst
│   ├── code_of_conduct.rst
│   ├── conf.py
│   ├── index.rst
│   ├── make.bat
│   ├── Makefile
│   ├── model.rst
│   ├── readme.rst
│   ├── requirements.txt
│   ├── _static
│   │   └── custom_cookietemple.css
│   └── usage.rst
├── .editorconfig
├── environment.yml
├── exploding_springfield
│   ├── data_loading
│   │   ├── data_loader.py
│   ├── exploding_springfield.py
│   ├── mlf_core
│   │   ├── mlf_core.py
│   │   └── __pycache__
│   │       └── mlf_core.cpython-38.pyc
│   ├── model
│   │   ├── model.py
├── .flake8
├── .gitattributes
├── .github
│   ├── ISSUE_TEMPLATE
│   │   ├── bug_report.md
│   │   ├── feature_request.md
│   │   └── general_question.md
│   ├── pull_request_template.md
│   └── workflows
│       ├── lint.yml
│       ├── pr_to_master_from_patch_release_only.yml
│       ├── publish_docker.yml
│       ├── publish_docs.yml
│       ├── sync.yml
│       └── train_cpu.yml
├── .gitignore
├── LICENSE
├── mlf_core.cfg
├── .mlf_core.yml
├── MLproject
├── README.rst
└── .readthedocs.yml
```

Removed some unrelated stuff.

**Comment by Zethson** [comment]
@Emiller88 It looks fine. It's really just the flake8 that you need to fix.

**Comment by Zethson** [comment]
tree

```
├── AUTHORS.rst
├── CHANGELOG.rst
├── CODE_OF_CONDUCT.rst
├── Dockerfile
├── docs
│   ├── authors.rst
│   ├── changelog.rst
│   ├── code_of_conduct.rst
│   ├── conf.py
│   ├── index.rst
│   ├── make.bat
│   ├── Makefile
│   ├── model.rst
│   ├── readme.rst
│   ├── requirements.txt
│   ├── _static
│   │   └── custom_cookietemple.css
│   └── usage.rst
├── environment.yml
├── exploding_springfield
│   ├── data_loading
│   │   ├── data_loader.py
│   ├── exploding_springfield.py
│   ├── mlf_core
│   │   └── mlf_core.py
│   ├── model
│   │   ├── model.py
├── LICENSE
├── mlf_core.cfg
├── MLproject
└── README.rst
```

@Emiller88 statement is the same. It's fine.
There's not even a flake8 error. I don't know what I posted earlier.

Maybe I did not pull.
I would be happy to merge this PR now. @Emiller88 fine with you or still thinking that there's something wrong?

**Comment by Emiller88** [comment]
Nope that's fine with me! Thanks!

**Pull request merged**
